#!/bin/bash

function build () {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
	cd /home/i/forks/eos
    else
	cd /Users/johndebord/forks/eos
    fi
    ./eosio_build.sh
    # ./eosio_build.sh -o Debug
}

function tester () {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
	cd /home/i/forks/eos/build/unittests
    else
	cd /Users/johndebord/forks/eos/build/unittests
    fi
    # ./unit_test
    # ./unit_test --log_level=all --run_test=api_tests/transaction_tests -- --verbose

    # ./unit_test --log_level=message --run_test=api_tests/deferred_transaction_tests
    # ./unit_test --log_level=message --run_test=api_tests/crypto_tests
    # ./unit_test --log_level=message --run_test=api_tests/memory_tests
    # ./unit_test --log_level=message --run_test=api_tests/extended_memory_test_page_memory_exceeded -- --verbose
    ./unit_test --log_level=message --run_test=api_tests/print_tests
    # ./unit_test --log_level=message --run_test=api_tests/types_tests
    # ./unit_test --log_level=message --run_test=api_tests/permission_usage_tests
}

if [ "$1" = "b" ]
then
    build
elif [ "$1" = "t" ]
then
    tester
elif [ "$1" = "a" ]
then
    build;
    tester;
else
    echo "Invalid option"
    echo "Usage: et [b | t | a]"
    echo "b == build | t == test | a == all"
    exit 1
fi
