#!/bin/bash

function build () {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
	cd /home/i/forks/eos
    else
	cd /Users/johndebord/forks/eos
    fi
    ./eosio_build.sh
}

function tester () {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
	cd /home/i/forks/eos/build/unittests
    else
	cd /Users/johndebord/forks/eos/build/unittests
    fi
    ./unit_test
}

if [ "$1" = "b" ]
then
    build
elif [ "$1" = "t" ]
then
    tester
elif [ "$1" = "a" ]
then
    build;
    tester;
else
    echo "Invalid option"
    echo "Usage: et [b | t | a]"
    echo "b == build | t == test | a == all"
    exit 1
fi
